### PR TITLE
Fixed translation of temperaments' names

### PR DESCRIPTION
**Pull request by oleg68**
Resolves: #1104

This is an alternative fix of #1104 instead of #1139

### CODE REVIEW

**Comment by oleg68** [comment]
@rousseldenis could you add @kerkovits as a reviewer of this PR?

**Review by larspalo — APPROVED** [review]

**Comment by kerkovits** [comment]
In src/core/temperaments/GOTemperamentList.cpp, the switch from wxTRANSLATE to wxT results in that gettext will not extract the names of temperaments as translatable strings.

**Comment by oleg68** [comment]
> In src/core/temperaments/GOTemperamentList.cpp, the switch from wxTRANSLATE to wxT results in that gettext will not extract the names of temperaments as translatable strings.

Yes, you are right. I reverted this change.

**Comment by kerkovits** [comment]
I tested your build. It does not work as intended. In src/core/temperaments/GOTemperamentList.cpp, there are numerous lines looking like `group = _("Some string");`. These strings appear as submenus under the menu temperament, and they are always rendered in English regardless of the locale. (The reason is that the source now calls function `_();` before initializing the locale.)

**Comment by oleg68** [comment]
@kerkovits I moved translation of temperaments groups too.

**Comment by oleg68** [comment]
@kerkovits Have you managed to test the last version intermediate? You can download it from https://github.com/oleg68/GrandOrgue-official/actions/runs/2959025636

**Comment by kerkovits** [comment]
I checked your sources and downloaded the last build. Thank you for your hard work, I think, it is perfect. I did not have time to check it yesterday. I closed the other pull request being obsolete.

**Comment by oleg68** [comment]
@kerkovits Thank you

@rousseldenis Could you approve this PR?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
