### PR TITLE
Renewed a default GO version during cmake build

### PR DESCRIPTION
**Pull request by oleg68**
Resolves: #14

Earlier cmake used `0.3.1` as the base and concatenated the release version had been taken from svn.

Now we assign the release version manually.

I've introduced the file `version.txt` where the current release version is stored.

Now cmake by default takes the version from `version.txt` and uses 0.YYMMDD as a build version.

During automatic builds on github VERSION and BUILD_VERSION are calculated from git tags and commit history.

In the future  (#711) I'm going to implement automatic git tagging when version.txt is being changed.

### CODE REVIEW

**Comment by larspalo** [comment]
I see you slightly adjusted the build numbering from what we discussed earlier and what your previous solution was. I guess that we still will set the build type number to -1 and adjust the release number when we do the actual releases, right, or did we just drop that part completely and have only a date based last part?

Also, what happens if intermediate builds are triggered the same day?

**Comment by oleg68** [comment]
> I see you slightly adjusted the build numbering from what we discussed earlier and what your previous solution was.

This PR does not affect automatic builds on github, because they go with -DVERSION and -DBUILD_VERSION passed. They still have 3.2.0-0.<small number> for intermediate builds and 3.2.0-1 for the release.

But what version to use with local build, when you run cmake or build-on-linux.sh manually?

My approach is 3.2.0-0.<something>, where <something> differs from any github autobuilds. I've made YYMMDD, but maybe to make 'local' (3.2.0-0.local) is better?

**Review by larspalo — APPROVED** [review]

**Comment by oleg68** [comment]
@larspalo, may be change to `local`?

**Comment by larspalo** [comment]
@oleg68 I can live with whichever, a .local ending is fine for me. If someone wants to change it they can override it at build time. Personally I can imagine overriding it to whatever branch (name) I'm testing at the moment just to know what the build is supposed to do.

**Comment by oleg68** [comment]
> @oleg68 I can live with whichever, a .local ending is fine for me. If someone wants to change it they can override it at build time. Personally I can imagine overriding it to whatever branch (name) I'm testing at the moment just to know what the build is supposed to do.

Chanded to `0.local`. I like your idea to use the branch name as a part of BUILD_VERSION

**Review by larspalo — APPROVED** [review]

**Comment by oleg68** [comment]
@rousseldenis  could you approve this pr?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
