### PR TITLE
Fixed uncompatibility with recent linux distros https://github.com/GrandOrgue/grandorgue/issues/1480

### PR DESCRIPTION
**Pull request by oleg68**
Resolves: #1480

As was discussed in #1480, I added building the `grandorgue-wx32` package that depends on wxWidgets 3.2 instead of 3.0. The new packages may be downloaded from https://github.com/oleg68/GrandOrgue-official/actions/runs/4811195352.

Installing `grandorgue-wx32` with dnf or apt should uninstall the old package `grandorgue` and vice versa.

If something does not work with 3.2 as expected please create separate issues for adoption grandorgue to 3.2.

### CODE REVIEW

**Comment by vpoguru** [comment]
When trying to install the package [grandorgue-wx32_3.11.0-1.4_amd64.deb](https://github.com/oleg68/GrandOrgue-official/suites/12479063912/artifacts/665153279) on Ubuntu 23.04 I see the following error message:

Unable to install grandorgue-wx32:
Error while installing package: parsing file */var/lib/dpkg/tmp.ci/-control' near line 8 package 'grandorgue-wx32'

**Comment by oleg68** [comment]
@vpoguru please try https://github.com/oleg68/GrandOrgue-official/actions/runs/4811195352

**Comment by vpoguru** [comment]
Now I get the error message (right after starting the installation package):

Unable to install grandorgue-wx32:
The following packages have unmet dependencies:

Unfortunately, it is not clear from the error message which dependencies are missing.

**Comment by oleg68** [comment]
@vpoguru could you try it from the command line:
```
apt-get update
apt-get install ./grandorgue-wx32_3.11.0-1.6_amd64.deb
```

(change `./` to the actual path where you have unpacked the deb file).

**Comment by vpoguru** [comment]
@oleg68,

Many thanks! You nailed it!

I downloaded the package again and followed your installation instructions. Successfully. I then uninstalled GO and tried to install it again by double clicking on the deb package. Again success.

I do not know what was wrong before.

**Comment by oleg68** [comment]
@larspalo @rousseldenis could you approve this PR?

**Review by larspalo — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
