### PR TITLE
Moved GOEventDistributor::ControlChanged to GOEventHandlerList::SendControlChanged

### PR DESCRIPTION
**Pull request by oleg68**
Toward to removing dependencies on GOOrganController from model I removed the method GOEventDistributor::ControlChanged and replaced it with GOEventHandlerList::SendControlChanged.

No GO behavior should be changed.

### CODE REVIEW

**Comment by oleg68** [comment]
@larspalo @rousseldenis could you approve this PR?

**Comment by larspalo** [comment]
@oleg68 As I tested this PR, I noticed again a strange thing with the default to engaged noise effects. They start fine, but the first time I de-activate them nothing happens. The control is visibly switched off but the noise itself isn't. It requires another activation and de-activation before it's working as it should.

**Comment by oleg68** [comment]
@larspalo after some testing I found that
1. The bug you mentioned was also existing before this PR. It's reason that the GORank::PreparePlayback was clearing velocities had been set when the stop had been engaged
2. I can not answer where it was introduced, but [the last commit](https://github.com/GrandOrgue/grandorgue/pull/1420/commits/f30ccd81eabd27f60150b55c01144049aa85c23d) in #1420 also fixes this problem.

So after merging this PR and #1420 there won't be the bug.

**Comment by larspalo** [comment]
> So after merging this PR and #1420 there won't be the bug.

Ok, I don't doubt that. The functionality in #1420 does work as it should. I'll approve this so that we can move forward.

**Review by larspalo — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
