### PR TITLE
Add support for building against system-wide RtAudio and RtMidi libraries

### PR DESCRIPTION
**Pull request by svillemot**
Note that this patch is part of my ongoing work to create an official Debian package for GrandOrgue (official from Debian’s perspective, of course).

### CODE REVIEW

**Comment by oleg68** [comment]
@svillemot, please add an entry in CHANGELOG.md.

**Comment by svillemot** [comment]
> @svillemot, please add an entry in CHANGELOG.md.

Done.

**Review by oleg68 — APPROVED** [review]

**Comment by oleg68** [comment]
@larspalo could you look at this PR?

**Comment by larspalo** [comment]
@oleg68 We don't have any current changes/patches against the RtAudio/RtMidi source right? If so, we could even change the order and check for a system wide version first and then if not found for a supplied version, right?

**Comment by oleg68** [comment]
> @oleg68 We don't have any current changes/patches against the RtAudio/RtMidi source right? 

Yes, we don't.

> If so, we could even change the order and check for a system wide version first and then if not found for a supplied version, right?

I haven't catch your idea. What order are you talking about? No there is a variable `USE_INTERNAL_RTAUDIO` that switches between internal and external rt in the same way as `USE_INTERNAL_PORTAUDIO`.

And Merry Christmass!

**Comment by larspalo** [comment]
Merry Christmas!

My thoughts were that in this PR the in source RtAudio and RtMidi is default (ON). Since we're not actively maintaining any changes in the libraries anymore we could as well have this as OFF by default and recommend using distribution supplied versions instead.

**Review by larspalo — APPROVED** [review]

**Pull request merged**
