### PR TITLE
Fixed help issues

### PR DESCRIPTION
**Pull request by oleg68**
Resolves: #1066 

A help window has been opened from a modal window is not compatible from one has been opened from modeless window.

This PR differentiates them and checks and closes the old help window if it is not good.

Also some help-related code has been extracted from the `GOFrame` class.

### CODE REVIEW

**Review by larspalo — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Comment by paolo2504** [comment]
> Resolves: #1066
> 
> A help window has been opened from a modal window is not compatible from one has been opened from modeless window.
> 
> This PR differentiates them and checks and closes the old help window if it is not good.
> 
> Also some help-related code has been extracted from the `GOFrame` class.

Oleg

I see new version 3661 does fix bug 1 and bug 3 as referenced in my original post #1066 but not the bug 2.

Here follows how to reproduce it.
1. do File/Settings and click the Help button in whatever tab: the underlaying taskbar is still not selectable and you have to move the Help dialog outside it to be able to choose menu items. 

Try also this (ex-bug 1):
1. select Help/Help from the taskbar menu
2. now select File/Settings: the Settings dialog opens but the underlaying Help dialog is no more selectable.
3. at this time, if you click on the Help button of whatever tab, you'll see the underlying Help dialog close while a new one is created; however, you cannot choose anything in the Help and the only thing you can do is Cancel the Settings dialog.


Definitely: bugs 1 & 3 "partially" fixed, bug 2 not fixed imho.

regards.

**Comment by paolo2504** [comment]
https://user-images.githubusercontent.com/50132661/166115495-5b8cf782-958b-41f5-a1a3-da11871c6bcf.mp4

**Comment by oleg68** [comment]
@paolo2504 I can not understand what do you find wrong in your video. The Setting dialog is `Modal` so you can not select anything in another windows until you close it. 

But you can open a help window from the settings dialog, and this window also becomes modal. After this the settings dialog is only partially working. You have to close the help window before continuing do something in the Settings. This is an intended behavior.

**Comment by paolo2504** [comment]
Oleg, leave it that way if you think it is correct. No problem my side. 
But I am sure this is wrong; I never saw a windows application/program where the help    dialogs are depending on the calling point/window. I can admit that since time Windows application link to internet Help pages… but when the Help manuals is installed locally , when you call it it’s always indipendent and you can work use the App and the Help applications at the same time. 
As I noted befeore, this is not crucial and I can get rid of it. 
Appreciate your effort.

**Pull request merged**
