### PR TITLE
Added capability of redefining ReleaseLength and IgnorePitch on each level of Organ Settings

### PR DESCRIPTION
**Pull request by oleg68**
I added new Organ Settings `ReleaseLength` and `IgnorePitch` available for setting at each level: Organ, Windchest, Rank and Pipe.

This PR includes all capabilities of #774, so that PR may be closed after this.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@pgcrowe

**Comment by larspalo** [comment]
@oleg68 I've tested the build from your fork and it seems to work as it should. I have a question about the implementation though. Why have you implemented the release tail shortening as a wxspinctrl in the organ settings dialog? Since the steps are fixed a wxchoice would perhaps make more sense and match the toolbar better. Also I think that 0 (zero) as value for release tail is somewhat misleading for actually meaning no shortening at all. The Max of the toolbar is at least suggesting what length the release will have. Just my first impressions after testing this...

**Comment by oleg68** [comment]
@larspalo If you insist, I may replace the spin control with the combo like in the toolbar.

But my concerns are
1. I don't like the combo in the toolbar because it does not fit to a small screen and it's difficult to navigate over it.
2. Other controls in the same dialog are spins. So now all they look similarly. The combo would look diferently.

**Comment by larspalo** [comment]
> @larspalo If you insist, I may replace the spin control with the combo like in the toolbar.
> 
> But my concerns are
> 
>     1. I don't like the combo in the toolbar because it does not fit to a small screen and it's difficult to navigate over it.
> 
>     2. Other controls in the same dialog are spins. So now all they look similarly. The combo would look diferently.

No, I won't insist very hard on it. As for your points though:

1. Would you consider a removal of the release tail shortening from the toolbar an improvement?
2. The Audio group right below the release tail is also a wxChoice in the organ settings dialog.

What I mostly find annoying is that the wording "Release Tail Length(ms): 0" actually means "no shortening is happening, the sample is played back as it is". A release tail length of 0 means to me: Don't play any release tail at all!

**Comment by larspalo** [comment]
Right, the audio group is a wxComboBox, the ones below are wxChoice...

**Comment by larspalo** [comment]
But in the toolbar the release tail is a wxChoice.

**Comment by larspalo** [comment]
@rousseldenis What's your opinion on this?

**Comment by oleg68** [comment]
> * Would you consider a removal of the release tail shortening from the toolbar an improvement?

No, I wouldn't. This feature is useful.

But I might be to replace it with a spin too.

Another possible improvment is capability of customising the toolbar contents. When a lot of elements exist (especially when there is a lot of audio output channels), they may not fit to a small screen. See #1036

> * The Audio group right below the release tail is also a wxChoice in the organ settings dialog.

You are right. wxCombo looks similar to wxChoice.

Finally, what is your suggestion:
- To leave the spin control in the organ settings now and to replace wxChoice with the spin in the toolbar in the future?
- To replace the spin control with the wxChoice in the organ settings?
- Some another option?

**Comment by oleg68** [comment]
> What I mostly find annoying is that the wording "Release Tail Length(ms): 0" actually means "no shortening is happening, the sample is played back as it is". A release tail length of 0 means to me: Don't play any release tail at all!

I wrote in the help: ``0 means playing  the full release section without a limit``

**Comment by larspalo** [comment]
@oleg68 I like your idea of a customizable toolbar in the future.

I understand that the wxChoice might have so many choices that they require scrolling, which might be uncomfortable. As I said I won't argue very much about it.

Yes, I understand how the feature works and I know what you wrote in the help. Still, just reading the words: "Release tail length (ms): 0" does mean something else, right? Reading: "Release tail length (ms): Max" means another thing that's closer to what is actually happening. That is basically the only thing I'm not comfortable with regarding this PR.

**Comment by oleg68** [comment]
@larspalo Will you be satisfied if I change `0` to the word `Max` in the edit field?

**Comment by larspalo** [comment]
> @larspalo Will you be satisfied if I change `0` to the word `Max` in the edit field?

Sure.

**Comment by oleg68** [comment]
> Sure.

OK. I'll do this a little bit later.

**Comment by oleg68** [comment]
@larspalo @rousseldenis I finished working with this PR. I display 0 as `Max` now.

Please review this PR.

**Comment by larspalo** [comment]
@oleg68 I really like the extra touch and effort to have the Max value and the - from (3000) and downwards, which makes much more sense than the toolbar wxChoice with Max to 50 upwards! Nice!

However, while testing it I had an issue when trying to import a .cmb file that I exported (with the same version of course). Though, it seems to not happen every time. The report on the command line is a warning subordinate process signal 11. The debugger of course doesn't help with the build from your fork, so I checked out the PR and made a debug build that gives this bt:

> GOOrganController::SetOrganModified (this=0x555558289860, modified=true)
>     at /home/lars/Sources/github/grandorgue/src/grandorgue/GOOrganController.cpp:145
> 145	    m_OrganModificationListener->OnIsModifiedChanged(modified);
> (gdb) bt
> #0  GOOrganController::SetOrganModified(bool)
>     (this=0x555558289860, modified=true)
>     at /home/lars/Sources/github/grandorgue/src/grandorgue/GOOrganController.cpp:145
> #1  0x0000555555662239 in GOOrganController::SetOrganModified()
>     (this=0x555558289860)
>     at /home/lars/Sources/github/grandorgue/src/grandorgue/GOOrganController.h:142
> #2  0x0000555555661643 in GODocument::LoadOrgan(GOProgressDialog*, GOOrgan const&, wxString const&) (this=0x555556817d50, dlg=0x7fffffffc790, 
>     organ=..., cmb=...)
>     at /home/lars/Sources/github/grandorgue/src/grandorgue/GODocument.cpp:101
> #3  0x00005555556508ad in GOFrame::LoadOrgan(GOOrgan const&, wxString const&)
>     (this=0x555555cc43f0, organ=..., cmb=...)
>     at /home/lars/Sources/github/grandorgue/src/grandorgue/GOFrame.cpp:596
> #4  0x000055555565329e in GOFrame::OnImportSettings(wxCommandEvent&)
>     (this=0x555555cc43f0, event=...)
>     at /home/lars/Sources/github/grandorgue/src/grandorgue/GOFrame.cpp:895
> #5  0x00007ffff7339641 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
>     at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
> #6  0x00007ffff7339743 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
> --Type <RET> for more, q to quit, c to continue without paging--
> #7  0x00007ffff7339aa0 in wxEvtHandler::TryHereOnly(wxEvent&) ()
>     at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
> #8  0x00007ffff7339b2b in wxEvtHandler::ProcessEventLocally(wxEvent&) ()
>     at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
> #9  0x00007ffff7339bd1 in wxEvtHandler::ProcessEvent(wxEvent&) ()
>     at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
> #10 0x00007ffff786bf2a in wxWindowBase::TryAfter(wxEvent&) ()
>     at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
> #11 0x00007ffff733995b in wxEvtHandler::SafelyProcessEvent(wxEvent&) ()
>     at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
> #12 0x00007ffff781ca2e in wxMenuBase::SendEvent(int, int) ()
>     at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
> #13 0x00007ffff7709743 in  ()
>     at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
> #14 0x00007ffff5d8c802 in g_closure_invoke ()
>     at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #15 0x00007ffff5da0814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #16 0x00007ffff5dabbbe in g_signal_emit_valist ()
>     at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #17 0x00007ffff5dac0f3 in g_signal_emit ()
>     at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #18 0x00007ffff640d842 in gtk_widget_activate ()
>     at /lib/x86_64-linux-gnu/libgtk-3.so.0
> --Type <RET> for more, q to quit, c to continue without paging--
> #19 0x00007ffff62db7d6 in gtk_menu_shell_activate_item ()
>     at /lib/x86_64-linux-gnu/libgtk-3.so.0
> #20 0x00007ffff62dba63 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
> #21 0x00007ffff646036f in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
> #22 0x00007ffff5d8ca56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #23 0x00007ffff5daadf1 in g_signal_emit_valist ()
>     at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #24 0x00007ffff5dac0f3 in g_signal_emit ()
>     at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #25 0x00007ffff640a9b3 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
> #26 0x00007ffff62c5ed8 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
> #27 0x00007ffff62c818b in gtk_main_do_event ()
>     at /lib/x86_64-linux-gnu/libgtk-3.so.0
> #28 0x00007ffff5faef69 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
> #29 0x00007ffff5fe20f6 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
> #30 0x00007ffff5ca117d in g_main_context_dispatch ()
>     at /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #31 0x00007ffff5ca1400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #32 0x00007ffff5ca16f3 in g_main_loop_run ()
>     at /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #33 0x00007ffff62c712d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
> #34 0x00007ffff7687575 in wxGUIEventLoop::DoRun() ()
>     at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
> --Type <RET> for more, q to quit, c to continue without paging--
> #35 0x00007ffff71edd41 in wxEventLoopBase::Run() ()
>     at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
> #36 0x00007ffff71b53da in wxAppConsoleBase::MainLoop() ()
>     at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
> #37 0x00005555555f37de in GOApp::OnRun() (this=0x5555559afc30)
>     at /home/lars/Sources/github/grandorgue/src/grandorgue/GOApp.cpp:153
> #38 0x00007ffff724173d in wxEntry(int&, wchar_t**) ()
>     at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
> #39 0x00005555555f2a20 in main(int, char**) (argc=1, argv=0x7fffffffde78)
>     at /home/lars/Sources/github/grandorgue/src/grandorgue/GOApp.cpp:31

The same settings file could be imported with current master and worked exactly as it should (with the individual pipe release tail shortening) without crashing like after building PR 1380.

**Comment by oleg68** [comment]
@larspalo I fixed the segfault: the reason was uninitialised `GOController::m_OrganModificationListener`

**Comment by oleg68** [comment]
@rousseldenis could you approve this PR?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
