### PR TITLE
Moved a common code to the GOMidiConfigurator::ShowConfigDialog

### PR DESCRIPTION
**Pull request by oleg68**
This is a next PR related to #1600.

Earlier lots of classes implemented GOMidiConfigurator::ShowConfigDialog() with quite similar code.

This PR
1. Moves the GOMidiConfigurator.h from `core/midi` to `grandorgue/midi` directory
2. Implements GOMidiConfigurator::ShowConfigDialog() with calling the new virtual GetMidi... methods

It is just refactoring. No GO behavior should be changed.

### CODE REVIEW

**Comment by larspalo** [comment]
@oleg68 I'm experiencing issues with the build from your actions for this PR. When closing GO it hangs and never really closes until I force it. When trying to change audio or midi settings or device in File->Settings GO again hangs (either when changing or when trying to close the dialog with ok to apply).

I'm starting to believe that there might have been a good reason why the audio earlier was stopped when the settings dialog was opened.

**Comment by larspalo** [comment]
Partially the issues seem to arise from audio device/drivers. When allowing pulseaudio (not starting with pasuspender) I can actually change audio/midi settings in File->Settings without a hang, but at close GO crashes with the message:

```
GrandOrgue: ../../../../src/cairo-region.c:428: cairo_region_destroy: Försäkran ”CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&region->ref_count)” falsk.
Avbruten (SIGABRT) (minnesutskrift skapad)
```

**Comment by larspalo** [comment]
Some more testing show a similar result as in the crash I reported in #1636 which makes it very likely that there's nothing wrong with this PR, but something further back instead.

**Comment by oleg68** [comment]
@larspalo please create a separate issue about a crash on closing GO.

**Review by larspalo — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
