### PR TITLE
Release 3.7.0

### PR DESCRIPTION
**Pull request by oleg68**
Afrer merging #1151

### CODE REVIEW

**Comment by organplayer** [comment]
Hallo,

where is download?

Aart

**Comment by rousseldenis** [comment]
> Hallo,
> 
> where is download?
> 
> Aart

@organplayer not yet. When this is merged, the release will be available

**Comment by organplayer** [comment]
Okay,  thank you for quick response.

Aart

Op ma 8 aug. 2022 21:46 schreef Denis Roussel (ACSONE) <
***@***.***>:

**Review by larspalo — APPROVED** [review]

**Comment by oleg68** [comment]
@rousseldenis could you approve this PR?

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@oleg68 could you remember me the flow for release? Do you create release from tag on GitHub interface?

**Comment by oleg68** [comment]
@rousseldenis merging this PR should automatically create a release tag. But it didn't happen now. Something went wrong...

**Comment by rousseldenis** [comment]
> @rousseldenis merging this PR should automatically create a release tag. But it didn't happen now. Something went wrong...

I saw in the tag actions that release step is skipped. I saw too that there is an error in calc_ver. Something with git fetch --unshallow

**Comment by rousseldenis** [comment]
@oleg68 I saw that the tag is exsiting yet before merging : https://github.com/GrandOrgue/grandorgue/releases/tag/3.7.0-0

Created in May

**Comment by rousseldenis** [comment]
> > @rousseldenis merging this PR should automatically create a release tag. But it didn't happen now. Something went wrong...
> 
> I saw in the tag actions that release step is skipped. I saw too that there is an error in calc_ver. Something with git fetch --unshallow

@oleg68 See there : https://github.com/GrandOrgue/grandorgue/runs/7791289941?check_suite_focus=true

**Comment by oleg68** [comment]
> @oleg68 I saw that the tag is exsiting yet before merging : https://github.com/GrandOrgue/grandorgue/releases/tag/3.7.0-0
> 
> Created in May

`-0` is a prerelease tag. The release tag is `-1`. It is created automatically with  https://github.com/GrandOrgue/grandorgue/blob/master/build-scripts/for-github/autotag.sh when the first line of CHANGELOG.md contains a correct release header.

The reason is absence of the release header in the CHANGELOG.md. Seems I deleted it ocasionally when was rebasing. 

I restored it in #1157.

**Comment by rousseldenis** [comment]
> > @oleg68 I saw that the tag is exsiting yet before merging : https://github.com/GrandOrgue/grandorgue/releases/tag/3.7.0-0
> > Created in May
> 
> `-0` is a prerelease tag. The release tag is `-1`. It is created automatically with https://github.com/GrandOrgue/grandorgue/blob/master/build-scripts/for-github/autotag.sh when the first line of CHANGELOG.md contains a correct release header.
> 
> The reason is absence of the release header in the CHANGELOG.md. Seems I deleted it ocasionally when was rebasing.
> 
> I restored it in #1157.

Great, I looked in build.yml script but not yet in autotag one.

**Pull request merged**
