### PR TITLE
Fixed Building PerfTests

### PR DESCRIPTION
**Pull request by oleg68**
This is the first commit for fixing performance-test related problems #868

- Renamed `perftest` to `GrandOrguePerfTest`
- Removed dependencies on the GrandOrgue application. The new classes `GOLogicalRect` and `GOResizable` were introduced
- Added unconditional building of GrandOrguePerfTest and packaging to the client distribution
- Renamed `perftest.cpp` to `GOPerfTest.cpp`
- Fixed sume failures when running the perftest.

No GrandOrgue behaviour should be affected.

There is still a remaining task: GrandOrguePerfTest can not be easy used on Windows because now it depends on graphical components and windows doesn't consider it as a console application.
For resolving this I need to split the current grandorgue code to a graphical and a graphicless parts and to move the graphicless to from `grandorgue` to `core` like it has been done with #949. It may require a lot of works.

@larspalo what do you think, should it be done in the same issue #868 or it is better to create a separate issue?

### CODE REVIEW

**Comment by larspalo** [comment]
@oleg68 I think it's excellent to separate the graphical parts, but it can certainly be done as a separate issue if you think this is complete enough for now. Just, for actually running the PerfTest one must point to the directory where the test files exist (test directory of GO source). Thus, the usage error message on line 198 should perhaps be changed to:

`wxLogError(wxT("Usage: GrandOrguePerfTest <GO source tree>/test"));`

Or, should we include the test files in the binary distibutions and automatically point to them and remove the need for argument to the program?

**Comment by oleg68** [comment]
> Or, should we include the test files in the binary distibutions and automatically point to them and remove the need for argument to the program?

Yes. I is a good idea. But the program parameter should rest for compatibility.

**Comment by oleg68** [comment]
@larspalo I added packaging the test wav files. `GrandOrguePerfTest` uses them unless another test dir is specified in the command line

**Review by larspalo — APPROVED** [review]

**Comment by oleg68** [comment]
@rousseldenis could you approve this PR?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
