### PR TITLE
Prepared for fixing MidiSendDialog

### PR DESCRIPTION
**Pull request by oleg68**
It is a preparing commit for #985. It contains mostly renaming according to the GO conventions.

GOMidiRecvDialog and GOMidiSendDialog now have m_MidiIn, m_MidiOut and m_MidiMap references instead of m_config

### CODE REVIEW

**Review by larspalo — APPROVED** [review]
I think we eventually should change the (clang) formatting for the casts so that we have a blankspace after the type. Ie. line 78 in GOMidiReceiverBase.cpp should become:

`m_events[i].type = (GOMidiReceiveMessageType) cfg.ReadEnum(`

to clearly state the intentions. This is not of any high priority, though.

**Comment by oleg68** [comment]
@rousseldenis could you approve this PR?

**Comment by oleg68** [comment]
@rousseldenis S'il vous plait, pouriez-vous approuver ce PR? Il-y-a beacoup des otres changements basee sur ce PR qui attandent.

**Comment by oleg68** [comment]
Excuse me, @rousseldenis. After several supplications to your in English and in French, I am constrained to merge this PR without more waiting for your approval.

**Comment by rousseldenis** [comment]
> Excuse me, @rousseldenis. After several supplications to your in English and in French, I am constrained to merge this PR without more waiting for your approval.
> 

No problem with that. This week has been busy for me and I don't want to be a 'click' machine, so to approve I need to read and understand (a little).

Thanks for this

**Pull request merged**
