### PR TITLE
Update Dutch translation /po/nl.po from branch AddDutch2

### PR DESCRIPTION
**Pull request by obw-go**
Update Dutch translation /po/nl.po from branch AddDutch2

Changes in a number of words that did not fit into the drawstop images on several panels and other improvements like replacing the Dutch word "lus" by the in Dutch most used word "loop" (as in the Dutch version of Audacity).

### CODE REVIEW

**Review by larspalo — APPROVED** [review]

**Comment by willeke1234** [comment]
There are still many mistakes and inconsistencies. Examples:
trigger -> trekker (trigger of a gun)
Copy current receive event -> Kopieer recent ontvangen event (Copy recently received event)
Mapping output -> Geluidsuitvoer in kaart brengen (Put sound output on a map)
Sound Output State -> Geluidsuitvoer (Sound output)
Upper bank -> Bovengrens (Upper limit)
Lower limit -> Lagere limiet (should be Ondergrens)
Manual Tuning -> Manuaalstemming (tuning of the manual)
The Event popup in the MIDI Event dialog is inconsistent

**Comment by obw-go** [comment]
@willeke1234 
Hi Willeke
Thanks for your feedback.
Could you please provide your alternative/better translations in Dutch for those strings?
wkr, Otto

**Comment by willeke1234** [comment]
The translation depends on the translation of the related strings and the context.

trigger -> activeren (Google Translate)
Copy current receive event -> Kopieer huidige ontvang-... (translation of event, in the in the sense of MIDI event)
Mapping output -> Uitvoertoewijzing (Google Translate)
Sound Output State -> Geluidsuitvoerstatus
Upper bank -> I don't know what it is, maybe Hoogste bank
Lower limit -> Ondergrens
Manual Tuning -> Handmatige stemming (I think, maybe it is a tuning of a manual per everything)

**Comment by obw-go** [comment]
@willeke1234 
Thx! I'll change it.
You wrote also: "The Event popup in the MIDI Event dialog is inconsistent"
How can I trigger this Event popup?
So far I simply used the GO software with some sample sets, but never went into technical details, so I have no idea...

**Comment by obw-go** [comment]
@larspalo 
Now I'm curious how I shoud proceed related to changes in a file that's object of a PR...
At first I make the changes in my local file. 
Can I after testing just replace the file on GitHub in the branch AddDutch2 by the most recent file with changes? Or do I have to close the PR, remove the branche AddDutch and start a new PR with a new branche?

**Comment by larspalo** [comment]
@obw-go Technically you can update/change the same file in the same branch that this PR was created from and it will automatically be included in this PR.

**Comment by obw-go** [comment]
> update/change the same file in the same branch

Thx! It works, because I can see the recent changes on the Files changed tab on this page...

**Comment by willeke1234** [comment]
>How can I trigger this Event popup?
I'm sorry, I'm a Mac user and I'm used to different terminology. It's called the Event dropdown in the Help and it displays the list of allowed events for the control. The list is already confusing in English.

**Review by oleg68 — APPROVED** [review]

**Pull request merged**
