### PR TITLE
Update Dutch Translation

### PR DESCRIPTION
**Pull request by obw-go**
Added new strings (e.g. related to new menu item 'Stops") and changing some strings related to the translation of the help file

### CODE REVIEW

**Comment by obw-go** [comment]
Added new strings (e.g. related to new menu item 'Stops") and changing some strings related to the translation of the help file

**Review by larspalo — APPROVED** [review]

**Review by oleg68 — APPROVED** [review]

**Comment by obw-go** [comment]
@oleg68 
Hi Oleg, 
I'm puzzled. Lars explained me that I had to put an updated file in a different branch of my owm fork and do the pull request from there. If I remember well, I did the PR from the branch obw-go-patch-1. I see that here the updated /po/po.nl with the changes I made still is placed. But to my surprise you merged the /po/po.nl from obw-go:master instead of from obw-go-patch-1. How could this happen? Or did I make a mistake in my last PR for /po/nl/po?

**Comment by larspalo** [comment]
@obw-go I didn't say that you had to, I was merely suggesting "best practise policies" when you're doing long term contributions. This PR, which I also approved of, is obviously coming from [obw-go:master](https://github.com/obw-go/grandorgue/tree/master) as you can see at the top - you created the PR from it as you had modified the files in the master branch to begin with. For a one time contribution this doesn't matter that much anyway.

**Comment by oleg68** [comment]
@obw-go I suggest you not to create PRs from [obw-go:master](https://github.com/obw-go/grandorgue/tree/master) but from branches. When I merge the PR I cannot select another branch.

**Comment by obw-go** [comment]
@larspalo @oleg68 
Ah - then I obviously made the mistake of putting the updated /po/nl.po in the branch obw-go-patch-1, but then doing the PR from the master.... I understand the ratio of letting the master of my fork be a copy of the master from GrandOrgue and put changed files in branches in my fork. Now I need to improve my practice for launching the PR from the right branch.
Thanks for your patience and help!

**Pull request merged**
