### PR TITLE
Added support of negative y-axis adjustment of manual keys https://github.com/GrandOrgue/grandorgue/issues/1485

### PR DESCRIPTION
**Pull request by oleg68**
Resolves: #1485

I allowed to specify negative values for YOffset_KEYTYPE and Key999YOffset.

### CODE REVIEW

**Review by larspalo — CHANGES_REQUESTED** [review]
@oleg68 You do realize that the issue in #1485 is caused by not understanding how things can be done in GrandOrgue and being willing to adapt to it? It's happening when someone is just looking at how things are done in hw and expect GO to behave in exactly the same way, when the things already could be done by just doing it the opposite way with the already existing implementation... (offsetting the naturals instead and possibly need to re-calculate some positions from the hw offsets to get the same exact placement). But in the end, as such, I have nothing really against the possibility to adjust the y value of key positioning in the negative direction.

However, what I **really** do want you to change is the phrasing of the title of the PR and the line in changelog so that it simply states that it's to allow negative y-axis adjustment of manual keys. Just so that it's clear that this is not a feature to just imitate Hauptwerk behavior.

**Comment by eturpault** [comment]
In Hauptwerk format, each key is placed in an absolute manner with LeftXPosPixels and TopYPosPixels attributes. There are no offset attributes.
To convert this HW absolute placement in GO format, the TopYPosPixels value of the first key of the keyboard (usually a natural key) can be used to set the PositionY attribute of the Manual, then each next key of the keyboard is placed relatively to this PositionY value with the YOffset attribute.
In order to use only positive YOffset values, it should be necessary to parse the TopYPosPixels values of all the keys of the keyboard to memorize the lowest Y value, then use it to set PositionY and parse again the keys of the keyboard to place them relatively to PositionY.
The first approach is more simple to implement and faster to execute that the second one.

**Comment by larspalo** [comment]
> The first approach is more simple to implement and faster to execute that the second one.

Totally beside the point, and for a computer/app of **very little** concern. The point is: the desired effect was already possible to achieve, you just didn't want to do it that way! That said, I'm not at all against implementing negative y-axis adjustments as a feature in GO, in this case just the phrasing of the motivation for it.

**Comment by eturpault** [comment]
The change being simple to make in GO, yes I would prefer it to be done in GO rather than in OdfEdit. And it is good to take advantage of this kind of opportunity to enlarge the configuration possibilities of the GO ODF format.

**Comment by oleg68** [comment]
> owever, what I **really** do want you to change is the phrasing of the title of the PR and the line in changelog so that it simply states that it's to allow negative y-axis adjustment of manual keys

Fixed

**Review by larspalo — CHANGES_REQUESTED** [review]
The display works perfectly, however the mouse rectangle seems to not really have changed from the default position to the new displayed position with this PR (whereas with the older positive YOffset it is). Thus, when clicking on the offset position or above on the bitmap, nothing happens. Also, the displayed keychange for the on state only updates to the not offset default position. Perhaps check the bounding box calculations?

**Comment by larspalo** [comment]
[TestYOffsetManuals.zip](https://github.com/GrandOrgue/grandorgue/files/11311802/TestYOffsetManuals.zip)

**Comment by oleg68** [comment]
@larspalo I fixed processing mouse events

**Review by larspalo — APPROVED** [review]
Now it works as expected!

**Comment by oleg68** [comment]
@rousseldenis could you approve this PR?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
