### PR TITLE
Dutch translation of the help file:     help/nl.po

### PR DESCRIPTION
**Pull request by obw-go**

### CODE REVIEW

**Comment by obw-go** [comment]
Dutch translation of the help file:     help/nl.po

**Comment by obw-go** [comment]
Dutch translation of the help file:     help/nl.po

**Comment by larspalo** [comment]
I think you should remove the po/nl.po file from this PR as it has its own already.

**Comment by obw-go** [comment]
> I think you should remove the po/nl.po file from this PR as it has its own already.

@larspalo 
I thought I did, but then the po/nl.po file was deleted from my fork directory...., so I have to experiment more to find out how I can remove po/nl.po from the pull request that regards help/nl.po....

**Comment by larspalo** [comment]
@obw-go We use git for version control. The general workflow that I (and I think most other developers) use for GO to keep changes separate from each other is:

1. Don't do any changes/work on the master branch of your own fork. Just keep that branch updated against the official repo at all times.
2. Create new branches for every separate feature you're working on and commit only relevant changes to each. In your case you could for instance have one UpdateDutchTranslation branch and one AddDutchHelp branch.
3. Create PR from each branch to the official repo

Having separate branches for the features and a "vanilla" master allows for having the different file versions separate from each other.

It might be possible to work only through the Github UI, but I think that most of us do the most work on a local copy of our fork first. So, on your local copy a brand new branch from the master branch (when you're on it) can be created by executing:

`git checkout -b newBranchName`

somewhere inside the GO repository tree and you'll be moved to that new branch at the same time. To change what branch you're presently on whenever you want (when not wanting to create a new) you'd just run:

`git checkout branchToChangeTo`

And note that to check/test your changes in the binary (program) for a certain branch make sure to run the **make** command to have a build done on that branch. Normally it's not necessary to have separate build directories and run _cmake_ for each, but for each branch you'll need to make sure to run the **make** command to have a build with the changes from that branch (only).

To push your changes from the local computer to the fork on Github you run:

`git push origin branchToPush`

Then you can create the PR from your fork/branch to official GO repo in the Github UI.

Do note that I've put imaginary branch names that try to explain the reason in the commands, the actual names would of course need to change according to situation! There are a lot more things to learn with using git and I'm personally not much beyond the "newbie" stage myself...

**Comment by obw-go** [comment]
@larspalo 
Hi Lars,
It's a pretty complicated story you wrote...
It seems that following the 1.2.3. steps from the beginning of your message did the trick altready for a PR regarding the /help/nl.po translation only...
So now I have to find out how I can remove this PR...
wkr, Otto

**Comment by obw-go** [comment]
Let's see if this works: Close the PR...

**Pull request closed without merging**
