### PR TITLE
Add Dutch translation updated strings /po/nl.po from branch AddDutch

### PR DESCRIPTION
**Pull request by obw-go**
Add Dutch translation updated strings /po/nl.po from branch AddDutch

### CODE REVIEW

**Comment by oleg68** [comment]
@obw-go I cannot merge this PR because your branch AddDutch was created before last changes of po/nl.po in master.

Could you rebase the branch `AddDutch` on top of the upstream master and resolve the conflicts?

**Comment by oleg68** [comment]
1. Add `https://github.com/GrandOrgue/grandorgue.git` as a remote named `upstream`
    ``git remote add upstream https://github.com/GrandOrgue/grandorgue.git``
2. Fetch all the master changes
    ``git fetch upstream``
3. Rebase the `AddDutch` branch on top of the upstrea/master
    ``git rebase upstream/master AddDutch``
    Some conflicts will be indicated.
4. Resolve the conflicts, following to https://docs.github.com/en/get-started/using-git/resolving-merge-conflicts-after-a-git-rebases
5. When you finish, complete the rebase
    ``git rebase --continue``
6. If the rebase breaks due new conflicts, repeat the steps 4 and 5.
7. Push the new branch state to your fork:
    ``git push --force``
8. Check this page that there is no conflicts indicated.

**Comment by obw-go** [comment]
> 1. git remote add     ..... and all the other git commands....

Where on the GitHub site I can type all these commands?
Or do I have to type them under Ubuntu?

**Comment by oleg68** [comment]
> > 1. git remote add     ..... and all the other git commands....
> 
> Where on the GitHub site I can type all these commands? Or do I have to type them under Ubuntu?

You have to do this in the command line on your local computer under Ubuntu or under Windows.

**Comment by obw-go** [comment]
> one step forward        and one step back

@oleg68 
Thanks to Willeke I saw that one of the changes I thought would be also in the /po/nl.po file, appeared to be missing, I think it's best to close this PR.
From reading around about branches I learn also that is't good practice to remove branches after using them for a PR, so I suppose that when I remove all the branches both from GitHub and from my local computer and start again with the most recent file /po/nl.po I have on my Windows PC where I use poedit, I will be able to find out what is right and what is missing...

**Pull request closed without merging**
