### PR TITLE
Feature/remove gui from core

### PR DESCRIPTION
**Pull request by oleg68**
This is a the last preparing PR for #949

The reason why GrandOrgueTool does not work on windows is that the OS considers this application as `Graphical`, not as `Condole`.

For marking this application console I have to remove all dependencies on graphical libraries.

So, in this PR
1. Moved all graphical classes from `core` to `grandorgue`
2. Modified CmakeLists for only `src/grandorgue` would depend on graphical wx libraries `html`, `net`, `adv`, `core`, and `src/core` would depend on only the `base` wx library
3. Renamed classes: `wxGaugeAudio` to `GOAudioGauge`, `OrganSelectDialog` to `GOSelectOrganDialog`
4. Added an intermediate class `GOLogicalColour` that doesn't depend on wxColour for using in `src/core`

No GrandOrgue behavior should be changed

### CODE REVIEW

**Review by larspalo — APPROVED** [review]

**Comment by oleg68** [comment]
@rousseldenis could you approve this PR?

**Comment by oleg68** [comment]
@rousseldenis S'il vous plait, pouriez-vous approuver ce PR?

**Comment by oleg68** [comment]
@rousseldenis I'm sorry but I have to merge this PR without your approval for avoiding conflict in the next PRs

**Comment by rousseldenis** [comment]
I'm on holidays for now so don't have plenty access to my emails. Don't hesitate if it blocks something

**Pull request merged**
