### PR TITLE
Moved Initialisation of General and Divisional templates from GOOrganController to GOOrganModel

### PR DESCRIPTION
**Pull request by oleg68**
In order to eliminating usage of GOOrganController I moved storing and initialisation of GOGeneralCombination GODivisionalCombination from GOOrganController to GOOrganModel.

It is jost refactoring. No GO controller should be changed.

### CODE REVIEW

**Comment by larspalo** [comment]
When I test this PR I get lots of errors in the log about faulty combination posts that all relate to Couplers. Even though the errors are logged, the combinations seem to work anyway.

**Comment by oleg68** [comment]
@larspalo I managed to reproduce the log messages and fixed two (old) bugs. But the extra log messages still appear when loading old presets. The reason was a reference to not-existent couplers from the preset.

After saving a new preset the errors disappear.

**Comment by oleg68** [comment]
@larspalo The error messages you mentioned relates to the virtual couplers, that do not exist in ODF and are provided by the `Couplers` panel.

Now the virtual couplers are created *after* initialisation of General and Divisional templates, so this PR breaks saving virtual coupler states in the combinations. It need more works to restore this capability.

**Comment by oleg68** [comment]
For fixing saving virtual couplers I need at first merging #1576

**Pull request closed without merging**
