### PR TITLE
Rewrote GOSelectOrganDialog with the GOSimpleDialog

### PR DESCRIPTION
**Pull request by oleg68**
This is a preparatory PR for the next commit for #1663

This PR reimplementing the Organ Selection dialog with `GOSelectOrganDialog`.

As a result
- it receives the right icon
- it's position and size are stored
- it receives the `Help` button

### CODE REVIEW

**Comment by larspalo** [comment]
@oleg68 Ok, the loading dialog size is remembered now, which is good. But the user selected width of the columns are not. It would be better to have a more dynamic layout that expand to fit available width instead of the absolute column widths currently used.

**Comment by oleg68** [comment]
@larspalo I'm planning to implement saving the column sizes in a future PR (for both this dialog and Settings/Organs). This PR only replaces the diagog class and does nothing with the internal elements.

Do you agree that GO behavior has not become worse with this PR? If yes, please approve this PR for I could submit a next enchancement.

**Review by larspalo — APPROVED** [review]
I'll approve as this is clearly one step towards a better implementation and it's not worse than the current one!

**Comment by oleg68** [comment]
@rousseldenis could your approve this pr?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
