### PR TITLE
Updates copyright headers

### PR DESCRIPTION
**Pull request by oleg68**
See also #1414

### CODE REVIEW

**Review by larspalo — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
I think I've already talked about this.

To avoid a great commit diff each year, I suggest to modify the year only when the concerned file is modified.

This is more coherent as some files are not modified (on code side) through some years.

That's my two cents on this from my other projects contribution experience

**Comment by oleg68** [comment]
Then we will forget to modify the copyright.

Is there any pre-commit hook that checks for the correct year?

**Comment by rousseldenis** [comment]
> Then we will forget to modify the copyright.
> 
> Is there any pre-commit hook that checks for the correct year?

That can exist if a template can be provided as configuration. I can look at

**Comment by rousseldenis** [comment]
> Then we will forget to modify the copyright.

The year is not crucial for it. License kind (AGPL/GPL... )more.

**Comment by rousseldenis** [comment]
I found this referenced on pre-commit site : https://github.com/Lucas-C/pre-commit-hooks#insert-license

**Pull request merged**
