### PR TITLE
Increasing the limit of number of ranks from 400 to 999

### PR DESCRIPTION
**Pull request by oleg68**
Discussed at https://github.com/GrandOrgue/grandorgue/discussions/680

### CODE REVIEW

**Review by larspalo — APPROVED** [review]
Nice touch updating the help too, thanks!

**Review by rousseldenis — APPROVED** [review]

**Comment by oleg68** [comment]
@rousseldenis because Lars wants to recruit @Jean-Gabriel1982, is it possible to add him as a reviewer? I couldn't find this option.

**Comment by oleg68** [comment]
Agree. I think we should to wtite CONTRIBUTORS.md with a step-by-step instruction that would start with very easy steps and would allow to be involved.

**Comment by rousseldenis** [comment]
> @rousseldenis because Lars wants to recruit @Jean-Gabriel1982, is it possible to add him as a reviewer? I couldn't find this option.

I think everybody can review.

Apart of that, I think we can add some teams with different rights (not so many to begin simple)

**Review by Jean-Gabriel1982 — APPROVED** [review]

**Pull request merged**
