### PR TITLE
Fix size increase as needed #713

### PR DESCRIPTION
**Pull request by larspalo**
Attempt to fix sizing issue.

### CODE REVIEW

**Comment by oleg68** [comment]
@larspalo 
1. Please enable Github Actions in your fork. I'd like to get the intermediate build from your fork and test it before approval.
2. Please add an entry to the CHANGELOG.md in the same PR (if you commit ant push it to the same branch in your fork, it will appear here automatically).

**Comment by larspalo** [comment]
@oleg68 I've tried to enable the workflow action of builds in my fork. Please check if it's working as it should.

**Comment by oleg68** [comment]
1. Seems it does not work: `Paths` became resizable but the file choose controls are still narrow:
go-settings-narrow
go-settings-wide
 
 2. After it be fixed, "Defaults and Initial Settings" help picture also should be updated with the new image.

**Comment by oleg68** [comment]
> I've tried to enable the workflow action of builds in my fork. Please check if it's working as it should.

It works. I've already downloaded GO from your action and I'posted screenshots above.

**Comment by larspalo** [comment]
@oleg68 Please test if the new version behaves as you want it. I first just made sure the text inside the dir picker ctrl would be visible, in the latest version I made them expand to use all available space.

**Comment by oleg68** [comment]
Now it works as expected

**Review by oleg68 — APPROVED** [review]

**Comment by oleg68** [comment]
@rousseldenis could you aprove this pr?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
