### PR TITLE
Init locale before loading configuration

### PR DESCRIPTION
**Pull request by kerkovits**
Resolves https://github.com/GrandOrgue/grandorgue/issues/1104

### CODE REVIEW

**Review by oleg68 — CHANGES_REQUESTED** [review]
This may not work if the language is redefined in the settings.

**Comment by rousseldenis** [comment]
@kerkovits I think you should rebase on this master as the libwine build error has been solved

**Comment by kerkovits** [comment]
@rousseldenis I see, thank you. Nevertheless, I succeeded to build it, but it still does not work as intended. The initialization of the locale could be moved into GOConfig.cpp just before the initialization of temperaments. However, if the locale is not the default one, the method `GetLanguageId()` still does not enforce the value set in the configuration. It seems, that the locale is customized by `m_config->Load();` in GOApp.cpp, However, I cannot find this explicitly in `void GOConfig::Load()` found in GOConfig.cpp. It seems that initalization of the locale is still too early in the middle of GOConfig::Load().

**Comment by kerkovits** [comment]
https://github.com/GrandOrgue/grandorgue/pull/1164/ made this obsolete.

**Comment by oleg68** [comment]
@kerkovits Thank you

@rousseldenis Could you approve this PR?

**Pull request closed without merging**
