### PR TITLE
Changed default directories for Cache and Data

### PR DESCRIPTION
**Pull request by oleg68**
As discussed at https://github.com/GrandOrgue/grandorgue/discussions/934#discussioncomment-1957649

### CODE REVIEW

**Review by larspalo — APPROVED** [review]
To get the new defaults, the old must first be deleted - then the new directories get created just fine, they won't be with old settings present on the system.

**Comment by oleg68** [comment]
@rousseldenis something went wrong with the formatting.

I've installed pre-commit on my computer but seems git does not call it when I commit changes so the code remains not formatted properly: https://github.com/oleg68/GrandOrgue-official/actions

**Comment by rousseldenis** [comment]
> @rousseldenis something went wrong with the formatting.
> 
> I've installed pre-commit on my computer but seems git does not call it when I commit changes so the code remains not formatted properly: https://github.com/oleg68/GrandOrgue-official/actions

Did you launch 'pre-commit install' command before 'git commits (to be done once)?

Either, if already committed, you can launch 'pre-commit run -a' to relaunch it globally.

**Comment by rousseldenis** [comment]
@oleg68 So you succeeded?

**Comment by oleg68** [comment]
@rousseldenis Yes, I did.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
