### PR TITLE
Updating .md files with the new repository

### PR DESCRIPTION
**Pull request by oleg68**
resolves: #9

### CODE REVIEW

**Review by larspalo — COMMENTED** [review]
I've submitted another README suggestion. Otherwise no objections

**Comment by oleg68** [comment]
@larspalo Yes, your text is better.

P.S. After merging your PR we'll receive a conflict in this PR.

**Comment by larspalo** [comment]
But it should be possible to merge the other files and remove the README, right?

**Comment by oleg68** [comment]
No, I cannor remove it from the commit already posted. The right way is to update this PR with a newer README

**Comment by larspalo** [comment]
Ok, can we just edit your README with the content of mine then and remove my pull request?

**Comment by oleg68** [comment]
I think it's better for us to learn working with conflicts. So lets merge #12 before this

**Comment by larspalo** [comment]
Ok, so you should merge your pull request but at the conflict have something like theirs full or something like that?

**Comment by oleg68** [comment]
No. I cannot merge this PR untill the conflict is resolved.

**Comment by rousseldenis** [comment]
> Ok, can we just edit your README with the content of mine then and remove my pull request?

The good way to suggest modifications to an existing PR:

Create a fork of this if you haven't done it already.
Fetch that repo locally
Add Oleg repo as new remote locally.
Fetch
Create a new branch based on oleg's one (you can see its name on top of the PR).
Make modifications, commit and push on your repository.
Go on github's interface to your repository, you should see PR suggestion and push on Oleg repo.

When Oleg merges it, the first PR will be updated

**Comment by rousseldenis** [comment]
That's the complicated way.

If you want to suggest modifications, you can do it through review

**Review by larspalo — APPROVED** [review]
Tried to add my suggested changes of  the README...

**Comment by larspalo** [comment]
This is of course quite un-important changes in one file only, but this kind of things can easily happen on a bigger level in the future when we're working on different new features that require changes in the same files...

**Comment by rousseldenis** [comment]
The advantage also to work on external branches is that only main branches appears here(master/svn)

**Comment by rousseldenis** [comment]
Example of a modification branch based on this : https://github.com/oleg68/GrandOrgue-oficial/pull/1

**Comment by oleg68** [comment]
@larspalo  @rousseldenis  @nickappleton  May we merge this PR?

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
> @larspalo @rousseldenis @nickappleton May we merge this PR?

@oleg68 Did you see mine on your repo?

**Comment by oleg68** [comment]
@rousseldenis It is not good that if an author adds more commits to an already approved PR, this PR remains approved. Ii would be better that the PR became unapproved.

**Comment by rousseldenis** [comment]
> @rousseldenis It is not good that if an author adds more commits to an already approved PR, this PR remains approved. Ii would be better that the PR became unapproved.

In an ideal world :-) but GitHub cannot distinguish that

**Comment by oleg68** [comment]
@rousseldenis 

> In an ideal world :-) but GitHub cannot distinguish that

I've enabled the ``Dismiss stale pull request approvals when new commits are pushed`` option in https://github.com/GrandOrgue/grandorgue/settings/branch_protection_rules/21999310 for the world would become a little bit closier to an ideal.

**Comment by rousseldenis** [comment]
Greate, didn't know that option

**Pull request merged**
