### PR TITLE
Fixed wrong filename of the midi recorder file with Hungarian language settings https://github.com/GrandOrgue/grandorgue/issues/1644

### PR DESCRIPTION
**Pull request by oleg68**
Resolves: #1644

The filename pattern is translated. The hungarian translation was wrong.

### CODE REVIEW

**Review by larspalo — APPROVED** [review]

**Comment by kerkovits** [comment]
Good catch!

I am sorry for the mistake.

I think I should revise the translation according to the development of the software (esp. new strings).

**Comment by briff** [comment]
> Good catch!
> 
> I am sorry for the mistake.
> 
> I think I should revise the translation according to the development of the software (esp. new strings).

I will be happy to review the Hungarian translations, please tag me when you need it.

**Comment by oleg68** [comment]
@rousseldenis could you approve this PR?

**Review by rousseldenis — APPROVED** [review]
I approve but IMHO those kind of strings should not be translatable...

**Pull request merged**
