### PR TITLE
Renaming GOrgue classes and files

### PR DESCRIPTION
**Pull request by oleg68**
Resolves: #816

Ther are lots of changes but they are quite simple: only renaming classes and files.

### CODE REVIEW

**Comment by larspalo** [comment]
This was a hard one to read! Around file 106 the diff messes up with some of the files in what file actually changed name to what and that definitely makes more difficult than it usually is to follow along in the changes...

**Comment by larspalo** [comment]
There are (quite) a few files that have no prefix, mainly the ones for parts of different dialogs. They are kind of grouped together as they are already, but what are your thoughts about them eventually?

Also, quite understandably you have not yet implemented the folder re-structuring either... But that comes next, right?

**Comment by oleg68** [comment]
> This was a hard one to read! 

Yes, agree, That is why I didn't make any extra changes exept renaming.

> Around file 106 the diff messes up with some of the files in what file actually changed name to what and that definitely makes more difficult than it usually is to follow along in the changes...

Yes, but renaming classes requires changing in all files where they are used.

Sometimes GitHub does not catch the renaming and shows add/remove instead. I do not know how to fix it.

> There are (quite) a few files that have no prefix, mainly the ones for parts of different dialogs. They are kind of grouped together as they are already, but what are your thoughts about them eventually?

I agree with adding the prefix to the files and classes that do not have it, but it would make this PR harder to review. So I made only changes in the scope of #816 and nothing else. I'd prefer to add the prefix in a separate issue.

The one exception is the `GrandOrgueFile`. Because another class `GOrgueFile` already existed in the `core` subdirectory, I couldn't rename both classes to `GOFile`. So I renamed `GOrgueFile` to `GOFile` and `GrandOrgueFile` to `GODefinitionFile`.

> Also, quite understandably you have not yet implemented the folder re-structuring either... But that comes next, right?

Yes, I haven't it. I wait for merging this PR and then I'll take #834 in work.

**Comment by oleg68** [comment]
@larspalo @rousseldenis Could you approve this? Keeping this PR unmerged will raise a lot of conflicts in the future.

**Review by larspalo — APPROVED** [review]

**Comment by oleg68** [comment]
@rousseldenis please, approve this PR.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
