### PR TITLE
Updated Swedish translation.

### PR DESCRIPTION
**Pull request by larspalo**
Just an update of the Swedish .po file for translation.

### CODE REVIEW

**Review by oleg68 — APPROVED** [review]

**Comment by oleg68** [comment]
@larspalo I'm approving this PR, but unfortunatelly I cannot check the translation.

**Comment by larspalo** [comment]
@jason-barba I've updated the Swedish translation of GrandOrgue that you perhaps could check both here (the actual sv.po file) and in the intermediate build at https://github.com/larspalo/grandorgue/actions/runs/9943350137. If you have any thoughts, ideas or objections, feel free to share them.

**Comment by jason-barba** [comment]
Will do. Might take some days ...

**Comment by jason-barba** [comment]
@larspalo I am now back at home so I can take a look on the Swedish translation.
Q: Do I have to download the build to perform your request?

**Comment by larspalo** [comment]
@jason-barba To view only the changed strings you can just click on the "Files Changed" tab at the top (where you have "Conversation" to the far left). If you want to view the strings in context of a running version of GrandOrgue you'll need to download a suitable build from https://github.com/larspalo/grandorgue/actions/runs/9943350137 and run it.

**Comment by jason-barba** [comment]
What is the purpose/function om the ampersand in för example Ne&d?

**Comment by larspalo** [comment]
> What is the purpose/function om the ampersand in för example Ne&d?

It's a menu mnemonic.

**Comment by jason-barba** [comment]
Ah! So the d in Ned should comply with din Down.

**Comment by jason-barba** [comment]
BTW how do you want my comments?

**Comment by larspalo** [comment]
@jason-barba You could just leave them in a message here.

**Comment by jason-barba** [comment]
@larspalo You will find my comments inline in the attached PDF. 
[Updated Swedish translation. by larspalo · Pull Request #1944 · GrandOrgue_grandorgue.pdf](https://github.com/user-attachments/files/16411150/Updated.Swedish.translation.by.larspalo.Pull.Request.1944.GrandOrgue_grandorgue.pdf)
Hope they will be of some use ;-)

I have not tried out the build, som there might be some missunderstandings from my side.

I find it troublesome to translate the short and distinct English words/sentences to Swedish because 1. we often use the English word in the Swedish context (Swenglish) and 2. a direct translation word for word may not yield a correct meaning in Swedish, sometimes very much on the contrary. I learned a lot when I was co-authoring a Swedish textbook in data communication.

**Comment by larspalo** [comment]
> I find it troublesome to translate the short and distinct English words/sentences to Swedish because 1. we often use the English word in the Swedish context (Swenglish) and 2. a direct translation word for word may not yield a correct meaning in Swedish, sometimes very much on the contrary.

Indeed, that's exactly why I didn't translate a lot of the MIDI messages. Some of the technical terms doesn't make sense to translate as we use the english word as a "borrowed" word anyway.

**Comment by larspalo** [comment]
@jason-barba The word "loop" is one of the terms I'm hesitant to change, both because it's technical term but also an accepted term in Swedish.

**Comment by larspalo** [comment]
> I can agree, but still dispute

Sure. In the case of the word "loop" it's however a Swedish word according to SAOL and since anyone with at least the slightest knowledge of an audio sample will understand what a loop is in that context I think I'll leave all such words as they are.

I also see some of your comments are about presently un-used strings. I won't change any of them right now.

I'll change all "sampling" related words to "sampel" except for resampling - "Omsampling".

**Comment by jason-barba** [comment]
Good! Glad to be able to contribute to the project :-)

**Comment by larspalo** [comment]
@jason-barba Thanks for your feedback. I've done some pretty extensive updating of the Swedish translation trying to be consistent and taking your suggestions into account. I suggest that you please try an intermediate build from https://github.com/larspalo/grandorgue/actions/runs/10150498087 (some of them can actually be tested without any actual installation, just download for instance https://github.com/larspalo/grandorgue/actions/runs/10150498087/artifacts/1752444517 and unpack it somewhere and run the binary in the /bin directory where you've unpacked it) so that you may see the strings (and choice of mnemonics) in context.

**Comment by jason-barba** [comment]
Just a quick look, but looks good. One thing thou, shouldn't "Arkiv/Settings .." be "Arkiv/Inställningar..."?

**Comment by larspalo** [comment]
@jason-barba (File->)Settings is one of the strings that cannot be translated.

**Comment by oleg68** [comment]
@jason-barba @larspalo have you finished or you still continue working?

**Comment by larspalo** [comment]
@oleg68 It's ready.

**Comment by oleg68** [comment]
@rousseldenis could you approve this pr?

**Comment by oleg68** [comment]
@rousseldenis Parce que in n'ya plus de travaux ici, je pense que il est miex de fusionner ce PR. Pourriez-vous approve ca? Merci.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
