### PR TITLE
Added a new set of manual key bitmaps and one new bitmap for drawstops.

### PR DESCRIPTION
**Pull request by larspalo**
As discussed in #1490 here comes a complete new set of bitmaps for manual keys and one new drawstop bitmap.

### CODE REVIEW

**Comment by oleg68** [comment]
@larspalo Why there is no automatic build for this changes at https://github.com/larspalo/grandorgue/actions ?

**Comment by larspalo** [comment]
> @larspalo Why there is no automatic build for this changes at https://github.com/larspalo/grandorgue/actions ?

@oleg68 It just failed with a GitHub Action internal error. Don't know why, though. Build work fine locally.

**Comment by larspalo** [comment]
@oleg68 It worked when I re-run the job. https://github.com/larspalo/grandorgue/actions/runs/4940037237 but the version number seem to be totally off, any idea as to why?

**Comment by oleg68** [comment]
You haven''t synched the version tags.

Run git fetch upstream --tags and then git push --tags.

**Review by oleg68 — APPROVED** [review]

**Comment by oleg68** [comment]
@larspalo please resolve conflict in CHANGELOG.md

**Comment by oleg68** [comment]
@rousseldenis could you approve this PR?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
