### PR TITLE
Make the Paths settings in the Options tab expandable

### PR DESCRIPTION
**Pull request by lubumbax**
~~Moved these settings to the bottom of the tab and~~ make the textboxes expandable

### CODE REVIEW

**Comment by oleg68** [comment]
@lubumbax Thank you for your PR, but

1. Moving it to another tab: `Paths` seems better than moving to the bottom of this tab
2. Such changes require corresponding changes to the help file and to the screenshots
3. We also need adding a line on top of CHANGELOG.md

**Review by larspalo — COMMENTED** [review]
I think we eventually must consider a complete re-make of the (general) settings dialog. I agree with having the paths dropddowns expandable (to be able to make sure they are visible), but the placement I think should wait until we've reached an agreement on how to proceed.

Would it be possible to re-make this PR? Include just the expanding change of the wxDirPickerCtrls. And remove the comments indicating old code. ;-)

**Comment by oleg68** [comment]
> but the placement I think should wait until we've reached an agreement on how to proceed.

So to remove moving to the bottom?

**Comment by oleg68** [comment]
> > > but the placement I think should wait until we've reached an agreement on how to proceed.
> > 
> > 
> > So to remove moving to the bottom?
> 
> Yes.

Agree.

**Comment by lubumbax** [comment]
> Would it be possible to re-make this PR? Include just the expanding change of the wxDirPickerCtrls. 

Are you suggesting opening a new PR? I can try amend the one commit in this one.

> And remove the comments indicating old code. ;-)

I can't see any such comments in SettingsOption.cpp . Do you mean the `// Paths` comment I added?

**Comment by larspalo** [comment]
> Are you suggesting opening a new PR? I can try amend the one commit in this one.

Yes, please, commit the changes to this PR, don't open a new.

**Comment by larspalo** [comment]
> Shall I remove the older `// Language` comment then, at line 41?

I would approve of that, since exactly the same word is in the line below. But it's not necessary to do that for this PR.

**Comment by oleg68** [comment]
@lubumbax 

I think a screenshot from OSx would be OK, but the theme must be light as all other screenshots.

Please enable actions at https://github.com/lubumbax/grandorgue/actions in order to allow GitHub to build the new version. After the build has occured, other people will be able to test it and to send you screenshots.

**Comment by lubumbax** [comment]
@oleg68 workflows enabled at `lubumbax/grandorgue`.

@larspalo 
> I think we eventually must consider a complete re-make of the (general) settings dialog. 

Maybe I can open a discussion for this? I can try to put the current options "in paper" and from there see what the options/choices are (maybe just leave them the way they are :).

**Review by oleg68 — APPROVED** [review]
Seems everything is all right

**Pull request merged**
