### PR TITLE
[IMP] Make build as default build subdirectory

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by larspalo** [comment]
You know you can use /build-for and under that you can create a /build-for/Release or whatever. I really don't mind adding more exceptions to .gitignore per se, but one can always ask if it's really necessary since other options exist... Also, you can add in your personal .git/info/exclude file anything you don't want under version control.

**Comment by oleg68** [comment]
@larspalo may be we rename `build-for` to `build`?

**Comment by larspalo** [comment]
> @larspalo may be we rename `build-for` to `build`?

Yes, of course! It will naturally require some changes in the build scripts too, but it's certainly doable.

**Comment by rousseldenis** [comment]
My problem I'm using vscode and default build dir is '<root>/build'.

**Comment by larspalo** [comment]
> My problem I'm using vscode and default build dir is '/build'.

Well, we all have our issues... As I said, we can rename the /build-for directory, or you can silently ignore it in .git/info/exclude like I do with the project files of Eclipse that i have a love/hate relationship with at the moment. ;-)

**Comment by rousseldenis** [comment]
> > My problem I'm using vscode and default build dir is '/build'.
> 
> Well, we all have our issues... As I said, we can rename the /build-for directory, or you can silently ignore it in .git/info/exclude like I do with the project files of Eclipse that i have a love/hate relationship with at the moment. ;-)

Ok, but two questions come in mind :

- Where are your builds generated to ?
- Is there an argument to pass to force build dir ?

**Comment by larspalo** [comment]
I know nothing about vscode. In Eclipse I first imported the git cloned repository as a general project, then added the c++ nature to it, created two build targets, one for Release and one for Debug that use the standard cmake command and builds into specified directories (build-for/Release) and (build-for/Debug). The standard CDT build just do a make command afterwards. I've been thinking about making a screencast about setting up Eclipse for GO development, but... 

As I said, I have a love/hate relationship to using Eclipse. Getting Eclipse to understand the wxWidgets code connection in the editor required additional steps that was a bit "hit or miss" in its configuration. Also, I don't like that for the git integration the .project and .cproject and ./settings files/directory must be present in the root. But when it's setup properly and everything works, it's pretty nice in many ways!

**Comment by rousseldenis** [comment]
> standard cmake command and builds into specified directories (build-for/Release) and (build-for/Debug).

Ok, so there is a config somewhere. I'll find it out.

> As I said, I have a love/hate relationship to using Eclipse. Getting Eclipse to understand the wxWidgets code connection in the editor required additional steps that was a bit "hit or miss" in its configuration. Also, I don't like that for the git integration the .project and .cproject and ./settings files/directory must be present in the root. But when it's setup properly and everything works, it's pretty nice in many ways!

I've been using Eclipse for years but is too heavy for memory/cpu. I have discovered VsCode one year ago and I'm very pleased on how is very easy to configure (evrything is accessible through a json). The advantage is also a huge community addons for almost everything. I did just download the Cmake addon, then click on Build and that's all.

**Comment by rousseldenis** [comment]
> > As I said, we can rename the /build-for directory
> 
> @rousseldenis May we do it in 3.4.2, not in the current release?

Of course. Didn't thought it would trigger debate ;-)

**Comment by oleg68** [comment]
@rousseldenis Could you make a context replacement `build-for` to `build` in the following files:

1. build-scripts/for-*/build-on*.sh
2. .github/workflow/build.yml
3. .gitignore

**Comment by rousseldenis** [comment]
@oleg68 Does it seems correct ?

**Comment by oleg68** [comment]
>  Does it seems correct ?

Almost does. Please add the entry to CHANGELOG.md

**Review by oleg68 — CHANGES_REQUESTED** [review]
Plase add the entry to CHANGELOG.md

**Comment by rousseldenis** [comment]
> Plase add the entry to CHANGELOG.md

Done

**Review by oleg68 — APPROVED** [review]

**Comment by oleg68** [comment]
@larspalo Could you approve this PR?

**Review by larspalo — APPROVED** [review]

**Pull request merged**
